=== signalwire/freeswitch/libs/unimrcp/conf/unimrcpserver.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:element name="unimrcpserver">
    <xsd:annotation>
      <xsd:documentation>UniMRCP server document</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="properties" minOccurs="0">
          <xsd:annotation>
            <xsd:documentation>Generic properties</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="ip" minOccurs="0">
                <xsd:complexType>
                  <xsd:attribute name="type" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ext-ip" minOccurs="0">
                <xsd:complexType>
                  <xsd:attribute name="type" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="components" minOccurs="0">
          <xsd:annotation>
            <xsd:documentation>Common components</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="resource-factory" minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>Factory of MRCP resources</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence maxOccurs="unbounded">
                    <xsd:element name="resource">
                      <xsd:complexType>
                        <xsd:attribute name="id" type="xsd:string" use="required" />
                        <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="sip-uas" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>SIP signaling agent</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="sip-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="sip-ext-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="sip-port" type="xsd:short" />
                    <xsd:element name="sip-transport" type="xsd:string" />
                    <xsd:element name="force-destination" type="xsd:boolean" default="false" minOccurs="0" />
                    <xsd:element name="disable-soa" type="xsd:boolean" default="false" minOccurs="0" />
                    <xsd:element name="extract-feature-tags" type="xsd:boolean" default="true" minOccurs="0" />
                    <xsd:element name="extract-call-id" type="xsd:boolean" default="false" minOccurs="0" />
                    <xsd:element name="extract-user-name" type="xsd:boolean" default="false" minOccurs="0" />
                    <xsd:element name="ua-name" type="xsd:string" minOccurs="0" />
                    <xsd:element name="sdp-origin" type="xsd:string" minOccurs="0" />
                    <xsd:element name="sip-t1" type="xsd:long" minOccurs="0" />
                    <xsd:element name="sip-t2" type="xsd:long" minOccurs="0" />
                    <xsd:element name="sip-t4" type="xsd:long" minOccurs="0" />
                    <xsd:element name="sip-t1x64" type="xsd:long" minOccurs="0" />
                    <xsd:element name="sip-message-output" type="xsd:boolean" />
                    <xsd:element name="sip-message-dump" type="xsd:string" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="type" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="rtsp-uas" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>RTSP signaling agent</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="rtsp-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="rtsp-ext-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="rtsp-port" type="xsd:string" />
                    <xsd:element name="resource-map">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="param" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:attribute name="name" type="xsd:string" use="required" />
                              <xsd:attribute name="value" type="xsd:string" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="max-connection-count" type="xsd:short" minOccurs="0" />
                    <xsd:element name="sdp-origin" type="xsd:string" minOccurs="0" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="type" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="mrcpv2-uas" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>MRCPv2 connection agent</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="mrcp-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="mrcp-port" type="xsd:string" />
                    <xsd:element name="max-connection-count" type="xsd:short" minOccurs="0" />
                    <xsd:element name="force-new-connection" type="xsd:boolean" minOccurs="0" />
                    <xsd:element name="rx-buffer-size" type="xsd:long" minOccurs="0" />
                    <xsd:element name="tx-buffer-size" type="xsd:long" minOccurs="0" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="media-engine" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>Media processing engine</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="realtime-rate" type="xsd:short" minOccurs="0" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="rtp-factory" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>Factory of RTP terminations</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="rtp-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="rtp-ext-ip" type="xsd:string" minOccurs="0" />
                    <xsd:element name="rtp-port-min" type="xsd:short" />
                    <xsd:element name="rtp-port-max" type="xsd:short" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="plugin-factory" minOccurs="0">
                <xsd:annotation>
                  <xsd:documentation>Factory of plugins (MRCP engines)</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence maxOccurs="unbounded">
                    <xsd:element name="engine">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="max-channel-count" minOccurs="0" />
                          <xsd:element name="param" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                              <xsd:attribute name="name" type="xsd:string" use="required" />
                              <xsd:attribute name="value" type="xsd:string" use="required" />
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:string" use="required" />
                        <xsd:attribute name="name" type="xsd:string" use="required" />
                        <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="settings" minOccurs="0">
          <xsd:annotation>
            <xsd:documentation>Settings</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="rtp-settings" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>RTP settings</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="jitter-buffer" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="adaptive" type="xsd:byte" />
                          <xsd:element name="playout-delay" type="xsd:long" />
                          <xsd:element name="max-playout-delay" type="xsd:long" />
                          <xsd:element name="time-skew-detection" type="xsd:byte" />
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="ptime" type="xsd:long" minOccurs="0" />
                    <xsd:element name="codecs">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:string">
                            <xsd:attribute name="own-preference" type="xsd:boolean" use="optional" />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="rtcp" minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="rtcp-bye" type="xsd:int" />
                          <xsd:element name="tx-interval" type="xsd:long" />
                          <xsd:element name="rx-resolution" type="xsd:long" />
                        </xsd:sequence>
                        <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="profiles" minOccurs="0">
          <xsd:annotation>
            <xsd:documentation>Profiles</xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="mrcpv2-profile" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>MRCPv2 profile</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="sip-uas" type="xsd:string" />
                    <xsd:element name="mrcpv2-uas" type="xsd:string" />
                    <xsd:element name="media-engine" type="xsd:string" />
                    <xsd:element name="rtp-factory" type="xsd:string" />
                    <xsd:element name="rtp-settings" type="xsd:string" />
                    <xsd:element name="resource-engine-map" type="xsd:string" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="mrcpv1-profile" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                  <xsd:documentation>MRCPv1 profile</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="rtsp-uas" type="xsd:string" />
                    <xsd:element name="media-engine" type="xsd:string" />
                    <xsd:element name="rtp-factory" type="xsd:string" />
                    <xsd:element name="rtp-settings" type="xsd:string" />
                    <xsd:element name="resource-engine-map" type="xsd:string" />
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="enable" type="xsd:boolean" use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="misc" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="sofiasip-logger" type="xsd:string" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="version" type="xsd:string" use="required" />
      <xsd:attribute name="subfolder" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== signalwire/freeswitch/libs/unimrcp/conf/unimrcpserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- UniMRCP server document -->
<unimrcpserver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="unimrcpserver.xsd"
               version="1.0">
  <properties>
    <!--
      If the attribute "type" is set to "auto", IP address is determined implicitly by the hostname.
      This is the default setting.
    -->
    <ip type="auto"/>

    <!--
      If the attribute "type" is set to "iface", IP address is determined by the specified name of
      network interface/adapter.
    -->
    <!-- <ip type="iface">eth0</ip>-->

    <!--
      IP address can also be specified explicitly.
    -->
    <!-- <ip>10.10.0.1</ip> -->

    <!-- <ext-ip>a.b.c.d</ext-ip> -->
  </properties>

  <components>
    <!-- Factory of MRCP resources -->
    <resource-factory>
      <resource id="speechsynth" enable="true"/>
      <resource id="speechrecog" enable="true"/>
      <resource id="recorder" enable="true"/>
      <resource id="speakverify" enable="true"/>
    </resource-factory>

    <!-- SofiaSIP MRCPv2 signaling agent -->
    <sip-uas id="SIP-Agent-1" type="SofiaSIP">
      <!--
        By default, "ip" and "ext-ip" addresses, set in the properties, are used. These parameters can
        explicitly be specified per "sip-uas" by means of "sip-ip" and "sip-ext-ip" correspondingly.
      -->
      <!-- <sip-ip>10.10.0.1</sip-ip> -->
      <!-- <sip-ext-ip>a.b.c.d</sip-ext-ip> -->
      <sip-port>8060</sip-port>
      <sip-transport>udp,tcp</sip-transport>
      <!-- <force-destination>true</force-destination> -->
      <!--
        This parameter can be used to disable the Sofia SIP SDP Offer/Answer Engine Module (soa).
        This should only be done when dynamic payload type negotiation is needed with MRCPv2 AND
        the clients only use the 'Basic Call' SDP Offer/Answer scenario. More complex scenarions
        will most probably not work with soa disabled.
      -->
      <!-- <disable-soa>true</disable-soa> -->
      <ua-name>UniMRCP SofiaSIP</ua-name>
      <sdp-origin>UniMRCPServer</sdp-origin>
      <!-- <sip-t1>500</sip-t1> -->
      <!-- <sip-t2>4000</sip-t2> -->
      <!-- <sip-t4>4000</sip-t4> -->
      <!-- <sip-t1x64>32000</sip-t1x64> -->
      <sip-session-expires>600</sip-session-expires>
      <sip-min-session-expires>120</sip-min-session-expires>
      <!-- <sip-message-output>true</sip-message-output> -->
      <!-- <sip-message-dump>sofia-sip-uas.log</sip-message-dump> -->
      <!-- <extract-feature-tags>false</extract-feature-tags> -->
      <!-- <extract-call-id>true</extract-call-id> -->
      <!-- <extract-user-name>true</extract-user-name> -->
    </sip-uas>

    <!-- UniRTSP MRCPv1 signaling agent -->
    <rtsp-uas id="RTSP-Agent-1" type="UniRTSP">
      <!--
        By default, "ip" and "ext-ip" addresses, set in the properties, are used. These parameters can
        explicitly be specified per "rtsp-uas" by means of "rtsp-ip" and "rtsp-ext-ip" correspondingly.
      -->
      <!-- <rtsp-ip>10.10.0.1</rtsp-ip> -->
      <!-- <rtsp-ext-ip>a.b.c.d</rtsp-ext-ip> -->
      <rtsp-port>1554</rtsp-port>
      <!-- <force-destination>true</force-destination> -->
      <resource-map>
        <param name="speechsynth" value="speechsynthesizer"/>
        <param name="speechrecog" value="speechrecognizer"/>
      </resource-map>
      <max-connection-count>100</max-connection-count>
      <inactivity-timeout>600</inactivity-timeout>
      <sdp-origin>UniMRCPServer</sdp-origin>
    </rtsp-uas>

    <!-- MRCPv2 connection agent -->
    <mrcpv2-uas id="MRCPv2-Agent-1">
      <!--
        By default, "ip" address, set in the properties, is used. This parameter can explicitly be
        specified per "mrcpv2-uas" by means of "mrcp-ip".
      -->
      <!-- <mrcp-ip>10.10.0.1</mrcp-ip> -->
      <mrcp-port>1544</mrcp-port>
      <max-connection-count>100</max-connection-count>
      <max-shared-use-count>100</max-shared-use-count>
      <force-new-connection>false</force-new-connection>
      <rx-buffer-size>1024</rx-buffer-size>
      <tx-buffer-size>1024</tx-buffer-size>
      <inactivity-timeout>600</inactivity-timeout>
      <termination-timeout>3</termination-timeout>
    </mrcpv2-uas>

    <!-- Media processing engine -->
    <media-engine id="Media-Engine-1">
      <realtime-rate>1</realtime-rate>
    </media-engine>

    <!-- Factory of RTP terminations -->
    <rtp-factory id="RTP-Factory-1">
      <!--
        By default, "ip" and "ext-ip" addresses, set in the properties, are used. These parameters can
        explicitly be specified per "rtp-factory" by means of "rtp-ip" and "rtp-ext-ip" correspondingly.
      -->
      <!-- <rtp-ip>10.10.0.1</rtp-ip> -->
      <!-- <rtp-ext-ip>a.b.c.d</rtp-ext-ip> -->
      <rtp-port-min>5000</rtp-port-min>
      <rtp-port-max>6000</rtp-port-max>
    </rtp-factory>

    <!-- Factory of plugins (MRCP engines) -->
    <plugin-factory>
      <engine id="Demo-Synth-1" name="demosynth" enable="true"/>
      <engine id="Demo-Recog-1" name="demorecog" enable="true"/>
      <engine id="Demo-Verifier-1" name="demoverifier" enable="true"/>
      <engine id="Recorder-1" name="mrcprecorder" enable="true"/>

      <!--
        Engines may have additional named ("max-channel-count") and generic (name/value) parameters.
        For example:
      -->
      <!--
      <engine id="Your-Engine-1" name="yourengine" enable="false">
        <max-channel-count>100</max-channel-count>
        <param name="..." value="..."/>
      </engine>
      -->
    </plugin-factory>
  </components>

  <settings>
    <!-- RTP/RTCP settings -->
    <rtp-settings id="RTP-Settings-1">
      <jitter-buffer>
        <adaptive>1</adaptive>
        <playout-delay>50</playout-delay>
        <max-playout-delay>600</max-playout-delay>
        <time-skew-detection>1</time-skew-detection>
      </jitter-buffer>
      <ptime>20</ptime>
      <codecs own-preference="false">PCMU PCMA L16/96/8000 telephone-event/101/8000</codecs>
      <!-- <codecs own-preference="false">PCMU PCMA L16/96/8000 PCMU/97/16000 PCMA/98/16000 L16/99/16000</codecs> -->
      <!-- Enable/disable RTCP support -->
      <rtcp enable="false">
        <!--
          RTCP BYE policies (RTCP must be enabled first)
            0 - disable RTCP BYE
            1 - send RTCP BYE at the end of session
            2 - send RTCP BYE also at the end of each talkspurt (input)
        -->
        <rtcp-bye>1</rtcp-bye>
        <!-- RTCP transmission interval in msec (set 0 to disable) -->
        <tx-interval>5000</tx-interval>
        <!-- Period (timeout) to check for new RTCP messages in msec (set 0 to disable) -->
        <rx-resolution>1000</rx-resolution>
      </rtcp>
    </rtp-settings>
  </settings>

  <profiles>
    <!-- MRCPv2 default profile -->
    <mrcpv2-profile id="uni2">
      <sip-uas>SIP-Agent-1</sip-uas>
      <mrcpv2-uas>MRCPv2-Agent-1</mrcpv2-uas>
      <media-engine>Media-Engine-1</media-engine>
      <rtp-factory>RTP-Factory-1</rtp-factory>
      <rtp-settings>RTP-Settings-1</rtp-settings>

      <!--
        Profile-based association of resources and engines with optional attributes.
        For example:
      -->
      <!--
      <resource-engine-map>
        <resource id="speechsynth" engine="Demo-Synth-1"/>
        <resource id="speechrecog" engine="Demo-Recog-1">
          <attrib name="n1" value="v1"/>
          <attrib name="n2" value="v2"/>
        </resource>
      </resource-engine-map>
      -->
    </mrcpv2-profile>

    <!-- MRCPv1 default profile -->
    <mrcpv1-profile id="uni1">
      <rtsp-uas>RTSP-Agent-1</rtsp-uas>
      <media-engine>Media-Engine-1</media-engine>
      <rtp-factory>RTP-Factory-1</rtp-factory>
      <rtp-settings>RTP-Settings-1</rtp-settings>
    </mrcpv1-profile>

    <!-- More profiles may follow. -->
  </profiles>
</unimrcpserver>
